version: '3.8'

services:
  web:
    build:
      context: landing-page-boilerplate
      dockerfile: landing-page-boilerplate/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app